matrix:
- name: Markdown
  language: hu_HU
  spellcheck:
    - hunspell
  hunspell:
    d: dictionaries/hu_HU/hu_HU
  dictionary:
    encoding: utf-8
    words:
      - .github/unique_hun_words.txt
  pipeline:
  - pyspelling.filters.markdown   # Markdown formázás eltávolítása
  - pyspelling.filters.html
  sources:
  - 'md/**/*.md'
  default_encoding: utf-8
