files:
  - README.md
dirs:
  - md
ignorePatterns:
  - pattern: 'https://www\.libreoffice\.org/.*'
  - pattern: 'https://groups\.oasis-open\.org/.*'
  - pattern: 'https://progress-bar\.xyz/.*'
  - pattern: 'https://lfg.hu/.*'
  - pattern: 'https://magus\.fandom\.com/.*'
