import type { Karakter } from './engine/types';
import { DEFAULT_SESSION } from './engine/types';

/** 8. szintű teszt karakter az ODS karakteralkotó referencia alapján */
export const testKarakter8: Karakter = {
  schema_version: 2,
  név: "Dorek a Toroni",
  tsz: 8,
  leírás: "Toroni zsoldos lovag",
  kor: 32,
  vallás: "",
  tulajdonságok: {
    erő: 3,
    edzettség: 3,
    ügyesség: 3,
    gyorsaság: 3,
    intelligencia: 1,
    emlékezet: 0,
    önuralom: 2,
    érzékenység: 0,
  },
  HM_TÉ: 15,
  HM_VÉ: 17,
  CM: 0,
  szilánk: 1,
  képzettségek: [
    { név: "Közelharc", szint: 6 },
    { név: "Kardvívás", szint: 8 },
    { név: "Rombolás", szint: 4 },
    { név: "Akrobatika", szint: 3 },
    { név: "Fájdalomtűrés", szint: 5 },
    { név: "Észlelés", szint: 6 },
    { név: "Nyelvtanulás", szint: 6 },
    { név: "Lovaglás", szint: 4 },
    { név: "Mászás", szint: 5 },
    { név: "Kvantikum", szint: 5 },
    { név: "Előadóművészet", szint: 5 },
    { név: "Etikett", szint: 5 },
    { név: "Értékbecslés", szint: 3 },
    { név: "Művészetismeret", szint: 5 },
    { név: "Városi jártasság", szint: 6 },
    { név: "Természetjárás", szint: 5 },
  ],
  fortélyok: [
    // Harci
    { név: "Merevvértviselet", fok: 3, spec_típus: "", spec_elem: "" },
    { név: "Harcos elme", fok: 2, spec_típus: "", spec_elem: "" },
    { név: "Gyors kezdeményezés", fok: 2, spec_típus: "", spec_elem: "" },
    { név: "Pajzshasználat", fok: 2, spec_típus: "", spec_elem: "" },
    { név: "Harckeret növelés", fok: 1, spec_típus: "", spec_elem: "" },
    { név: "Elpusztíthatatlan", fok: 2, spec_típus: "", spec_elem: "" },
    { név: "Kaszabolás", fok: 2, spec_típus: "", spec_elem: "" },
    { név: "Támadás erőből", fok: 1, spec_típus: "", spec_elem: "" },
    { név: "Fárasztás", fok: 1, spec_típus: "", spec_elem: "" },
    { név: "Mesterfegyver", fok: 2, spec_típus: "fegyver", spec_elem: "kard, lovag" },
    { név: "Mesterfegyver", fok: 1, spec_típus: "fegyver", spec_elem: "tőr" },
    // Általános
    { név: "Építészet", fok: 1, spec_típus: "", spec_elem: "" },
    { név: "Futás", fok: 1, spec_típus: "", spec_elem: "" },
    { név: "Szájról olvasás", fok: 1, spec_típus: "", spec_elem: "" },
    { név: "Éber alvó", fok: 1, spec_típus: "", spec_elem: "" },
    { név: "Kocsihajtás", fok: 1, spec_típus: "", spec_elem: "" },
    { név: "Keresés/rejtés", fok: 1, spec_típus: "", spec_elem: "" },
    // Kiemelt (többszörös)
    { név: "Kultúrkör", fok: 1, spec_típus: "kultúrkör", spec_elem: "dw00n" },
    { név: "Kultúrkör", fok: 1, spec_típus: "kultúrkör", spec_elem: "erv" },
    { név: "Kultúrkör", fok: 1, spec_típus: "kultúrkör", spec_elem: "py4r" },
    { név: "Kultúrkör", fok: 1, spec_típus: "kultúrkör", spec_elem: "dzs4d" },
    { név: "Helyismeret", fok: 1, spec_típus: "település", spec_elem: "Erion" },
    { név: "Helyismeret", fok: 1, spec_típus: "település", spec_elem: "Pyarron" },
    { név: "Helyismeret", fok: 1, spec_típus: "település", spec_elem: "Haonwell" },
    { név: "Helyismeret", fok: 1, spec_típus: "település", spec_elem: "Shulur" },
    // Szabad
    { név: "Gazdálkodás", fok: 1, spec_típus: "", spec_elem: "" },
    { név: "Kézműves: Lakatos", fok: 1, spec_típus: "", spec_elem: "" },
    { név: "Kihallgatás", fok: 1, spec_típus: "", spec_elem: "" },
    { név: "Színjátszás", fok: 1, spec_típus: "", spec_elem: "" },
    { név: "Éneklés", fok: 1, spec_típus: "", spec_elem: "" },
    { név: "Bűvészet", fok: 1, spec_típus: "", spec_elem: "" },
    { név: "Alkudozás", fok: 1, spec_típus: "", spec_elem: "" },
    { név: "Térképészet", fok: 1, spec_típus: "", spec_elem: "" },
  ],
  fortélyok_speciális: {
    analfabéta: false,
    apró_méretű_lény: false,
    tartós_sérülés_fok: 0,
    vakság: false,
    süketség: false,
  },
  hátterek: {
    faj: "Ember (Északi)",
    leíró: [],
    karma: [],
  },
  fegyverek: [
    { alap: "kard, lovag", név: "", anyag: "acél", idea: 0, mesterfegyver_fok: 2 },
    { alap: "tőr", név: "", anyag: "acél", idea: 0, mesterfegyver_fok: 1 },
  ],
  páncél: {
    alap: "bőr",
    név: "",
    fémalapanyag: "",
    idea: 0,
    kidolgozottság: "átlagos",
    sisak: false,
    végtagvédettség: 0,
    méret_illeszkedés: "passzol",
    rongálódás: 0,
  },
  felszerelés: { nagy_tárgyak: [] },
  jegyzetek: '',
  session: { ...DEFAULT_SESSION, aktív_páncél: true },
};

/**
 * Elvárt értékek az ODS referencia alapján — engine validáláshoz
 */
export const expected8 = {
  ÉP: 40,
  KÉ: 17,
  összes_kp: 408,
  összes_szekunder_kp: 160,
  összesen_kapott_kp: 568,
  kp_képzettségek: 224,
  kp_fortélyok: 150,
  kp_hm: 192,
  kp_cm: 0,
  elköltött_kp: 566,
  maradt_kp: 2,
  tulajdonság_pont_keret: 68,
  tulajdonság_pont_maradék: 0,
  max_HM: 34,
  max_CM: 16,
  manőver_alap: 4,
  max_manőver_pont: 5,
  kard_lovag: {
    TÉ: 47,
    VÉ: 74,
    SP: "11 V/S +1Á",
    támadások: 2,
  },
  páncél: {
    sfé_fizikai: 7,
    sfé_energia: 10,
    MGT: 2,
    lefedettség: 50,
  },
};
