name: Spell Check
on: [push]
jobs:
  hunspell:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Hunspell and Hungarian directionary
        run: |
          sudo apt-get update
          sudo apt-get install -y hunspell hunspell-hu

      - name: Running spellcheck in Hungarian
#        uses: github/spellcheck-action@v1
        uses: rojopolis/spellcheck-github-actions@0.49.0
        with:
          config: .github/spellcheck-config.json
