name: Spell Check
on: [push]
jobs:
  hunspell:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download latest Hungarian Hunspell dictionary
        run: |
          mkdir -p dictionaries/hu_HU
          curl -L -o dictionaries/hu_HU/hu_HU.dic_8859-2 https://raw.githubusercontent.com/LibreOffice/dictionaries/master/hu_HU/hu_HU.dic
          curl -L -o dictionaries/hu_HU/hu_HU.aff_8859-2 https://raw.githubusercontent.com/LibreOffice/dictionaries/master/hu_HU/hu_HU.aff

      - name: ISO-8859-2 to UTF-8 conversion for .aff and .dic files
        run: |
          iconv -f ISO-8859-2 -t UTF-8 dictionaries/hu_HU/hu_HU.aff_8859-2 > dictionaries/hu_HU/hu_HU.aff
          iconv -f ISO-8859-2 -t UTF-8 dictionaries/hu_HU/hu_HU.dic_8859-2 > dictionaries/hu_HU/hu_HU.dic

      - name: Install Hunspell and Hungarian directionary
        run: |
          sudo apt-get update
          sudo apt-get install -y hunspell hunspell-hu

      - name: Running spellcheck with Hunspell
        uses: rojopolis/spellcheck-github-actions@0.49.0
        with:
          config_path: .github/spellcheck-config.yaml
          task_name: Markdown

      - name: Remove .dic and .aff files
        run: |
          mkdir -p dictionaries/hu_HU
