import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import path from 'path';
import { createReadStream, existsSync, readFileSync } from 'fs';
import { execSync } from 'child_process';
import type { Plugin } from 'vite';

function serveDataPlugin(): Plugin {
  const dataDir = path.resolve(__dirname, '../data');
  const generateScript = path.join(dataDir, 'generate_tables.py');

  return {
    name: 'serve-data',
    buildStart() {
      // Regenerate tables once on dev server start / build start
      if (existsSync(generateScript)) {
        console.log('[serve-data] Generating tables from YAML sources...');
        execSync(`python3 "${generateScript}"`, { cwd: dataDir, stdio: 'inherit' });
      }
      // Generate metadata.json
      const metadataScript = path.resolve(__dirname, 'generate_metadata.py');
      if (existsSync(metadataScript)) {
        execSync(`python3 "${metadataScript}"`, { cwd: __dirname, stdio: 'inherit' });
      }
    },
    configureServer(server) {
      server.middlewares.use('/szilankrpg/data', (req, res, next) => {
        const filePath = path.join(dataDir, req.url ?? '');
        if (existsSync(filePath)) {
          const ext = path.extname(filePath);
          const mime: Record<string, string> = { '.json': 'application/json', '.yaml': 'text/yaml', '.yml': 'text/yaml' };
          res.setHeader('Content-Type', mime[ext] ?? 'text/plain');
          createReadStream(filePath).pipe(res);
        } else {
          next();
        }
      });
    },
  };
}

// Read metadata version (generated by buildStart)
function getVersion(): string {
  const metaPath = path.resolve(__dirname, 'public/metadata.json');
  if (existsSync(metaPath)) {
    try {
      const meta = JSON.parse(readFileSync(metaPath, 'utf-8'));
      return meta.version ?? '?';
    } catch { return '?'; }
  }
  return '?';
}

export default defineConfig({
  plugins: [react(), serveDataPlugin()],
  base: '/szilankrpg/',
  define: {
    __APP_VERSION__: JSON.stringify(getVersion()),
  },
  server: {
    host: true,
    watch: { usePolling: true, interval: 500 },
  },
});
